import PDFDocument from 'pdfkit';

export const generatePrescriptionPdfBuffer = ({
  prescription,
  patient,
  doctor,
}) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('AI Clinic Prescription', { align: 'center' }).moveDown();
    doc.fontSize(12);
    doc.text(`Patient: ${patient.name}`);
    doc.text(`Age / Gender: ${patient.age} / ${patient.gender}`);
    doc.text(`Doctor: ${doctor.name}`);
    doc.text(`Date: ${new Date(prescription.createdAt).toLocaleString()}`).moveDown();

    doc.fontSize(14).text('Medicines', { underline: true }).moveDown(0.5);
    prescription.medicines.forEach((medicine, index) => {
      doc
        .fontSize(12)
        .text(`${index + 1}. ${medicine} - ${prescription.dosage[index] || 'As advised'}`);
    });

    doc.moveDown().fontSize(14).text('Instructions', { underline: true }).moveDown(0.5);
    doc.fontSize(12).text(prescription.instructions || 'No additional instructions.');

    doc.moveDown().fontSize(14).text('AI Explanation', { underline: true }).moveDown(0.5);
    doc.fontSize(12).text(prescription.aiExplanation || 'No AI explanation generated.');

    doc.moveDown().fontSize(10).fillColor('gray').text('Generated by AI Clinic Management SaaS');
    doc.end();
  });